/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Record({
  'principal' : IDL.Principal,
  'score' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getBestScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'registerScore' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Record({ 'principal' : IDL.Principal, 'score' : IDL.Nat });
  
  return IDL.Service({
    'getBestScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'registerScore' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };